source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HermesLogger_Example', :exclusive => true do
  pod "HermesLogger", :path => "../"
end

target 'HermesLogger_Tests', :exclusive => true do
  pod "HermesLogger", :path => "../"
end
